### ISSUE TITLE
Bug: raise Exception("Number of expected symbols more than the time stamps"?

### ISSUE THREAD

**Issue by Gqwert123** [cywang97/StreamingTransformer#3]
Hi, sorry to disturbe you.
When I use my own corpus. when I use the off-line model align the ctc path. Sone instance got this bug. So can you tell me how to solve this problem.

`logit shape: (1220, 52)
59 52
Traceback (most recent call last):
  File "../../../espnet/bin/asr_recog.py", line 180, in <module>
    main(sys.argv[1:])
  File "../../../espnet/bin/asr_recog.py", line 176, in main
    viterbi_decode(args)
  File "/espnet/asr/pytorch_backend/asr_recog.py", line 177, in viterbi_decode
    align = model.viterbi_decode(feat[0][0], y)
  File "/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 253, in viterbi_decode
    align = viterbi_align(logit, y)[0]
  File "/espnet/nets/viterbi_align.py", line 26, in viterbi_align`

raise Exception("Number of expected symbols more than the time stamps"

sone instance frame not enough long

**Comment by cywang97** [comment]
Hi, viterbi alignment requires the length of utterance is larger than the length of the sentence. You can just skip the failed instances.
